"""Add threat_intel_context to phishing_analysis table

Revision ID: 1cf099bf102b
Revises: 09378c82cdac
Create Date: 2025-08-06 10:18:21.829066

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cf099bf102b"
down_revision: Union[str, Sequence[str], None] = "09378c82cdac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phishing_analysis", sa.Column("threat_intel_context", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phishing_analysis", "threat_intel_context")
    # ### end Alembic commands ###
